# Generated by Django 6.0 on 2025-12-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersettings_delete_aiassistant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_cd68de_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__b20cde_idx',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
